### ISSUE TITLE
Upgrade to CKAN 2.8.3

### ISSUE THREAD

**Issue by reubano** [openpeoria/AWS-CKAN#10]
https://aws.amazon.com/marketplace/pp/B07WHK45BM#pdp-support
https://helpdesk.links.com.au/kb/faq.php?id=15

**Comment by sottom** [comment]
@reubano  I think your EC2 instance at http://3.216.14.60/ is already running 2.8.3.

Here is the source HTML with the version in the meta tag.
![image](https://user-images.githubusercontent.com/18564176/80513700-ae16e300-893c-11ea-8907-60ccad08b08a.png)

**Comment by reubano** [comment]
Same version, but different release. `2.8.3_20200313` vs `2.8.3_20191021`.

**Comment by reubano** [comment]
This issue is top priority.

**Comment by sottom** [comment]
I'm not seeing a 2.8.3_20200313

Did you mean v.2.8.4 2020-04-15?

**Comment by reubano** [comment]
https://aws.amazon.com/marketplace/pp/B07WHK45BM

![Screen Shot 2020-05-01 at 11 24 51](https://user-images.githubusercontent.com/157864/80821565-9e96d480-8b9e-11ea-881b-f82ebec579fd.png)

**Comment by sottom** [comment]
This is finished. See the [docs](https://handbook.nerevu.com/upgrade-ckan-instance.html) for instructions.
