### ISSUE TITLE
Add new key pair

### ISSUE THREAD

**Issue by reubano** [openpeoria/AWS-CKAN#11]
I don't have `openpeoriakey.pem`, so for now add your own key...

![Screen Shot 2020-04-28 at 12 49 48](https://user-images.githubusercontent.com/157864/80520287-d4de1500-894e-11ea-8b87-621d7e1e1c7d.png)

![Screen Shot 2020-04-28 at 12 49 33](https://user-images.githubusercontent.com/157864/80520286-d4de1500-894e-11ea-8767-8abb67b84c64.png)

https://stackoverflow.com/a/60501637/408556

**Comment by sottom** [comment]
Solved. Created instructions [here](https://github.com/nerevu/handbook/pull/2).
