### ISSUE TITLE
Verify adding a dataset works

### ISSUE THREAD

**Issue by reubano** [openpeoria/AWS-CKAN#12]
https://docs.ckan.org/en/2.8/user-guide.html#adding-a-new-dataset

**Comment by sottom** [comment]
It worked after changing the owner of the `/var/shared_storage/ckan` folder to `apache:apache`.
I added these instructions to [the docs](https://handbook.nerevu.com/upgrade-ckan-instance.html).

**Comment by reubano** [comment]
That's odd. Was that documented anywhere?

**Comment by sottom** [comment]
Nope. I had to transfer that directory from the old instance, so I figured the owner or permissions were wonky after looking at some forums it worked after changing them.
