### ISSUE TITLE
Portal home page is missing the welcome image

### ISSUE THREAD

**Issue by reubano** [openpeoria/AWS-CKAN#13]
https://openpeoria.nerevu.com/

![Screen Shot 2020-05-09 at 12 06 13](https://user-images.githubusercontent.com/157864/81480339-c3b6c300-91ee-11ea-9d49-94b250ab8dbc.png)

- [ ] update docs with steps to ensure images and other related assets carry over across ckan updates

**Comment by sottom** [comment]
@reubano I figured out how to change the picture. Is there a specific picture you want me to use?

**Comment by reubano** [comment]
- Awesome, can you add the steps to this issue? 
- Use [this pic](https://www.meetup.com/gp-data-community/photos/29874030/#483890336)

**Comment by sottom** [comment]
# Adding Promoted Image to CKAN
1. Transfer your image from your local computer to the CKAN instance.
```bash
# replace the private key, the path to the image, and the IP address of the instance
scp -i "{private_key}" path/to/local/promoted-image.jpg ec2-user@{instance_ip_addressss}:~
```
2. SSH into your CKAN EC2 instance
3. Transfer the image to the images directory
```bash
# NOTE: /usr/lib/ckan/default/src/ckan/ckan/public/ is the default directory our AWS version of CKAN
sudo mv ~/promoted-image.jpg /usr/lib/ckan/default/src/ckan/ckan/public/base/images/
```
4. Edit the html page that references the promoted image. Change the src to the correct name.
```bash
sudo vim /usr/lib/ckan/default/src/ckan/ckan/templates/home/snippets/promoted.html
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# change {your_uploaded_image.jpg} to the file you uploaded
<img class="img-responsive" src="{{ h.url_for_static('/base/images/{your_uploaded_image.jpg}') }}" alt="Placeholder" width="420" height="220" />
```
5. Restart the server
```bash
sudo systemctl restart httpd
```
