### ISSUE TITLE
Create s3 bucket to hold COVID19 data

### ISSUE THREAD

**Issue by reubano** [openpeoria/AWS-CKAN#14]
- [x] make bucket public
- [x] make all objects [public by default](https://stackoverflow.com/questions/19176926/how-to-make-all-objects-in-aws-s3-bucket-public-by-default)

**Comment by sottom** [comment]
Done.
https://s3.console.aws.amazon.com/s3/buckets/nerevu-covid-data/

**Comment by sottom** [comment]
To make all the objects in a bucket public by default, you need to go to do the following:

1. Go to the bucket's `Permissions` tab
![image](https://user-images.githubusercontent.com/18564176/86049108-d095ad00-ba0e-11ea-928e-8513804dd7ca.png)

2. Click the `Block public access` button
3. Click `Edit` and then uncheck the `Block all public access`  button (this makes the bucket itself publicly accessible).
![image](https://user-images.githubusercontent.com/18564176/86049335-35510780-ba0f-11ea-82d7-46d7a2a3bd14.png)
4. Now click on the `Bucket Policy` button
5. Add the following json policy to the form and click save (this makes Objects in the bucket public by default):
```json
{
    "Version": "2012-10-17",
    "Id": "Policy1591372563727",
    "Statement": [
        {
            "Sid": "Stmt1591372557944",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::nerevu-covid-data/*"
        }
    ]
}
```
*NOTE: You will need to change the `Resource` section of the json policy to your respective bucket's ARN*
