### ISSUE TITLE
Enable s3 bucket versioning

### ISSUE THREAD

**Issue by reubano** [openpeoria/AWS-CKAN#15]
https://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html

**Comment by sottom** [comment]
Done

**Comment by sottom** [comment]
# Enabling Bucket Versioning

1. Go to the Bucket in AWS.
2. Click on Properties
3. Click Versioning
4. Click Enable Versioning
5. Save

![image](https://user-images.githubusercontent.com/18564176/86389207-36727680-bc53-11ea-90ba-3d5e43404266.png)
