### ISSUE TITLE
Integrate datapusher

### ISSUE THREAD

**Issue by reubano** [openpeoria/AWS-CKAN#17]
[datapusher](https://github.com/ckan/datapusher)

**Comment by reubano** [comment]
> Note that if you installed CKAN using the package install option then a DataPusher instance should be automatically installed and configured to work with your CKAN site.

Does this apply to us?

**Comment by sottom** [comment]
Yes, it is 'theoretically' already enabled.

![image](https://user-images.githubusercontent.com/18564176/85164460-9fa0c580-b221-11ea-93a3-dab970568000.png)

But it's not pushing anything automatically yet.

**Comment by sottom** [comment]
It looks like it might only work with CSV/XLSX data.
```
DataPusher is a standalone web service that automatically downloads any CSV or XLS (Excel) data files from a CKAN site's resources
```

![image](https://user-images.githubusercontent.com/18564176/85164683-f0b0b980-b221-11ea-9cee-4f763b21dec6.png)

That may have something to do with it, because we have JSON data.

**Comment by sottom** [comment]
That's the problem. [Datapusher only tries to automatically upload csv or xls files](https://docs.ckan.org/projects/datapusher/en/latest/using.html#triggering-pushes). So maybe we should convert our json to csv?

**Comment by reubano** [comment]
Yea, you can do so with [records2csv](https://github.com/reubano/meza/blob/94d19019805c114769d999c8ee53d5adec7f1863/meza/convert.py#L773) and [read_json](https://github.com/reubano/meza/blob/94d19019805c114769d999c8ee53d5adec7f1863/meza/io.py#L1081)

```python
>>> from io import StringIO
>>>
>>> from meza.io import read_json
>>> from meza.convert import records2csv
>>> 
>>> records = read_json(report)
>>> csv_report = records2csv(records)
>>> csv_data = csv_report.read()
```

So upload both `json` and `csv` formats to ckan

**Comment by sottom** [comment]
Do you want them in separate datasets? Like an `il-covid19-csv` group and an `il-covid19-json` group? Or just put them all in the same dataset?

**Comment by reubano** [comment]
Same data set

**Comment by reubano** [comment]
The above example should be good to go now, made a bunch of edits...

**Comment by sottom** [comment]
county (list)
        County, confirmed_cases, deaths, lat, lon, total_tested
    demographics (dict)
        age (list)
            age_group, count, deaths, tested
            demographics (dict)
                race (list)
                    color, count, deaths, description, tested
        gender (list)
            color, count, deaths, description, tested
        race (list)
            color, count, deaths, description, tested
    state (dict)
        confirmed_cases, deaths, testDate, total_tested


county-County, county-confirmed_cases

**Comment by sottom** [comment]
Split out lists of data into their own files.
