### ISSUE TITLE
Enable Data API button on Datasources

### ISSUE THREAD

**Issue by sottom** [openpeoria/AWS-CKAN#20]
Enable the data api button on datasources and make sure that the instructions produce working results (test the endpoints).

**Comment by sottom** [comment]
https://africaopendata.org/dataset/sensorsafrica-airquality-archive-kisumu/resource/8f4e417f-9831-47da-be3d-6969729bd4df

**Comment by sottom** [comment]
Resource html page here - `/usr/lib/ckan/default/src/ckan/ckan/templates/package/resource_read.html`

**Comment by sottom** [comment]
To enable the Data API button, I think we need to get the Datapusher extension working (see #17). The Data API button shows up by default ONLY if a resource is loaded into the Datastore. 

![image](https://user-images.githubusercontent.com/18564176/85162275-5733d880-b21e-11ea-9e38-c9598b54c954.png)

Uploading is currently a manual process by navigating to a resource, clicking `Manage`, `Datastore`, then `Upload to Datastore`. 
	
![image](https://user-images.githubusercontent.com/18564176/85162200-2a7fc100-b21e-11ea-963d-f61f92525b8a.png)

This manual upload works with the Hospital JSON data, but doesn't work with Zip or County JSON data because of the `color` key throws a `non-valid fieldname` error. It looks like it has too many quotes.

![image](https://user-images.githubusercontent.com/18564176/85162524-c14c7d80-b21e-11ea-8b9e-d57ad266884a.png)

We will need to get datapusher working and fix the JSON data we're pulling in to resolve this issue.

**Comment by sottom** [comment]
We will need to get datapusher working and fix the json data we're pulling in to get this working.

**Comment by reubano** [comment]
Alright, I just assigned #17 to you. Can you create an issue for the above error and then work on the hospital json data datapusher integration?

**Comment by sottom** [comment]
The new issue is #21

**Comment by sottom** [comment]
The Data API button is enabled by default with the AWS Marketplace CKAN instance we are using. It shows up after Datapusher adds uploaded data to the Datastore; however, [Datapusher only pushes CSV and XLS data](/lib/ckan/default/src/ckan/ckan/templates), so the Data API button only shows up automatically for those types of files. In order to get the button to show up, we need to add CSV data with our JSON data (see [this PR](https://github.com/openpeoria/covid-19-il-data-scraper/pull/11))

**Comment by sottom** [comment]
Reopened to allow the hook on a PR to close it automatically :P
