### ISSUE TITLE
Configure HTTPS

### ISSUE THREAD

**Issue by reubano** [openpeoria/AWS-CKAN#8]
Setup site so that it works on HTTPs automatically configured by LetsEncrypt

- [x] [SSL](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/SSL-on-amazon-linux-2.html)
  - [x] Prerequisites
  - [x] Step 1: Enable TLS on the Server (**partially complete**)
  - [x] Step 2: Obtain a CA-signed Certificate (**skipped**)
  - [x] Step 3: Test and Harden the Security Configuration (**skipped**)
  - [x] Troubleshooting
  - [x] Certificate Automation: Let's Encrypt with Certbot on Amazon Linux 2 (**partially complete**)
- [x] [site_url](https://helpdesk.links.com.au/kb/faq.php?id=11)

**Comment by reubano** [comment]
In the "Certificate Automation..." step, stuck on "Install and Run Certbot" 

```
Which names would you like to activate HTTPS for?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: openpeoria.nerevu.com
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel): 1
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for openpeoria.nerevu.com
Waiting for verification...
Challenge failed for domain openpeoria.nerevu.com
http-01 challenge for openpeoria.nerevu.com
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: openpeoria.nerevu.com
   Type:   unauthorized
   Detail: Invalid response from
   http://openpeoria.nerevu.com/.well-known/acme-challenge/S88thvVDLFoCJJzZjBrL60K6_HTlyfanBhOAJhqih4E
   [3.216.14.60]: "<html>\r\n<head><title>502 Bad
   Gateway</title></head>\r\n<body
   bgcolor=\"white\">\r\n<center><h1>502 Bad
   Gateway</h1></center>\r\n<hr><cen"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```

**Comment by reubano** [comment]
To restart server and get rid of the `502 Bad Gateway` error, run `service httpd restart`

**Comment by sottom** [comment]
This is finished. See instructions [here](https://handbook.nerevu.com/ckan-https.html).

**Comment by reubano** [comment]
[Just found this](https://github.com/ckan/ckan/wiki/SSL), can you make sure we have it all covered?

**Comment by sottom** [comment]
Sure thing. I did as much of this as I could. A lot of the configuration was written from scratch because most of the tutorials are written for Ubuntu.
